[package]
name = "litep2p"
description = "p2p library"
license = "MIT"
version = "0.1.0"
edition = "2021"

[build-dependencies]
prost-build = "0.11"

[dependencies]
async-trait = "0.1.66"
asynchronous-codec = "0.6.1"
bs58 = "0.4.0"
bytes = "1.4.0"
ed25519-dalek = "1.0.1"
futures = "0.3.27"
lazy_static = "1.4.0"
multiaddr = "0.17.0"
multihash = { version = "0.17.0", default-features = false, features = ["std", "multihash-impl", "identity", "sha2"] }
multistream-select = "0.12.1"
prost = "0.11.8"
protoc = "2.28.0"
rand = { version = "0.7.0", features = ["getrandom"] }
serde = "1.0.158"
snow = "0.9.2"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["compat", "io"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
unsigned-varint = { version = "0.7.1", features = ["codec", "asynchronous_codec"] }
yamux = "0.11.0"
zeroize = "1.5.7"
