[package]
name = "litep2p"
description = "p2p library"
license = "MIT"
version = "0.1.0"
edition = "2021"

[build-dependencies]
prost-build = "0.11"

[dependencies]
asynchronous-codec = "0.6.1"
async-trait = "0.1.66"
bs58 = "0.4.0"
bytes = "1.4.0"
ed25519-dalek = "1.0.1"
futures = "0.3.27"
futures-rustls = "0.22.2"
lazy_static = "1.4.0"
mockall = "0.11.4"
multiaddr = "0.17.0"
multihash = { version = "0.17.0", default-features = false, features = ["std", "multihash-impl", "identity", "sha2"] }
pin-project = "1.1.0"
prost = "0.11.8"
protoc = "2.28.0"
rand = { version = "0.8.0", features = ["getrandom"] }
rcgen = "0.10.0"
ring = "0.16.20"
s2n-quic = { version = "1.22.0", features = ["provider-tls-rustls"] }
serde = "1.0.158"
smallvec = "1.10.0"
snow = "0.9.2"
thiserror = "1.0.39"
tokio = { version = "1.26.0", features = ["full"] }
tokio-stream = "0.1.12"
tokio-util = { version = "0.7.7", features = ["compat", "io", "codec"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
trust-dns-resolver = { version = "0.22.0", features = ["tokio"] }
unsigned-varint = { path = "misc/unsigned-varint", features = ["codec", "tokio-util"] }
str0m = { path = "misc/str0m" }
webpki = "0.22.0"
x509-parser = "0.15.0"
yamux = "0.11.0"
yasna = "0.5.0"
zeroize = "1.5.7"
hex-literal = "0.4.1"
tokio-tungstenite = "0.19.0"
url = "2.4.0"
socket2 = "0.5.3"
simple-dns = "0.5.3"
uint = "0.9.5"
sha2 = "0.10.7"
stun = "0.4.4"
tinytemplate = "1.2.1"
hex = "0.4.3"

# Exposed dependencies. Breaking changes to these are breaking changes to us.
[dependencies.rustls]
version = "0.20.7"
default-features = false
features = ["dangerous_configuration"] # Must enable this to allow for custom verification code.

[dev-dependencies]
async-channel = "1.8.0"
libp2p = { version = "0.51.3", features = [
    "tokio",
    "dns",
    "identify",
    "macros",
    "mplex",
    "noise",
    "ping",
    "tcp",
    "kad",
    "websocket",
    "yamux",
    "quic",
]}
sc-network = { path = "/home/altonen/work/substrate/client/network", version = "0.10.0-dev" }

[profile.release]
debug = true
