reorder_imports = true
newline_style = "Unix"
chain_width = 80
spaces_around_ranges = false
match_arm_blocks = false
trailing_comma = "Vertical"
edition = "2021"
comment_width = 100
wrap_comments = true
